# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

m1 = Movie.create(title: "Empire", image: "https://wqvxrw-dm2305.files.1drv.com/y3mEWtsj7S2gLxBDYwKJR9r8rwPR5qNVMFU_bMhD04j0JqB-3r4xtJTpa5Yqhgs3y-0x8NVVmm_8lD36EwUv0GZfCS8hMzIXPJD60km9M_NYpfAvWVoMW19Sk8lMpU1q-BizJBabqgsuM1tMbuULivv8yH1ZwVhkQcC4kWijLHP1e8?width=242&height=292&cropmode=none", release_year: "2015", plot: "LUCIOUS LYON is the king of hip-hop. An immensely talented artist, the CEO of Empire Entertainment and a former street thug, his reign has been unchallenged for years. But all that changes, when he learns he has a disease that is going to render him crippled and incapacitated in a matter of three years. The clock is ticking, and he must groom one of his three sons to take over his crowning achievement, without destroying his already fractured family.")
m2 = Movie.create(title: "11.22.63", image: "https://xkvtrw-dm2305.files.1drv.com/y3mFZmyaLjh3jDmu2lKElXzWGJd5DIaCyR8s_yQwhLlzP7_CxWQ_NqlMWl_xK6RSEIGsDY_f6NjtXigFFwmXRIe1x3Tmi3K4M7e2-g3VaHG5KiuUBApQyVgxagH52n8hNHJTU2HXQeayGgg3EK1TFRz-uA1deGQt5SOrgb4fuC0sGg?width=242&height=292&cropmode=none", release_year: "2015", plot: "High school teacher Jake Epping travels back in time to prevent the assassination of President John F. Kennedy - but his mission is threatened by Lee Harvey Oswald, falling in love, and the past itself, which doesn't want to be changed and shouldn't be changed. ")
m3 = Movie.create(title: "And Then There Were None", image: "https://w6vdrw-dm2305.files.1drv.com/y3mYxhcLsTtWz0Zf-OW7hJcT2-Fh-lBndLBZYEZWXZTrUQTlgarU-6mktj0hqUewvV-1NvKumPzdvkgLYjdl2A1kLLDCSb3uqIGsCHazM2Bnn_PIhO0LBkVFvP-W_r2r6A8G-CmQ2FciQiY1BRhHUL4HWh4DsYQiafQVzMTEuLwWYc?width=242&height=292&cropmode=none", release_year: "2015", plot: "Ten strangers, drawn away from their normal lives to an isolated rock off the Devon coast. But as the mismatched group waits for the arrival of the hosts -- the improbably named Mr. and Mrs. U.N. Owen -- the weather sours and they find themselves cut off from civilization. Very soon, the guests, each struggling with their conscience, will start to die -- one by one, according to the rules of the nursery rhyme 'Ten Little Soldier Boys' -- a rhyme that hangs in every room of the house and ends with the most terrifying words of all: '... and then there were none.")
m4 = Movie.create(title: "Supergirl", image: "https://xkvzrw-dm2305.files.1drv.com/y3mK6b_E_Sy1HAxY_VnQAGvP2RTaV4fsfHQ9kywVw0xqmv1z2a7sFAmxphHHL_nt2EW4JSnkDu3lW7I17kC-KgGoL_gDTK9bMbVmNAVD4DlqY5JfoTauupru_XopbIy3fOc2xI-ON9snV12_oxZrND9VRhnny0VON23lQ-NkbYgrvs?width=242&height=292&cropmode=none", release_year: "2015", plot: "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism. ")
m5 = Movie.create(title: "Blindspot", image: "https://w6vurw-dm2305.files.1drv.com/y3mq1ZNpPc8qQEl57M1iegI3JxEH7z5yPGOKoQ439uM-QbM70UjeMVevWgCEps82djyCGb-ZZb3gg3fXIQi422uClkNc6CV1bPyb9fbiCrDs1eQEfMFSJUx8dmCGYBAoelsrmCZC5hkQBKuRFZgPO1V857MIGLVSLdGn1I0UH71Avs?width=242&height=292&cropmode=none", release_year: "2015", plot: "A vast international plot explodes when a beautiful Jane Doe is discovered naked in Times Square, completely covered in mysterious, intricate tattoos with no memory of who she is or how she got there. But there's one tattoo that is impossible to miss: the name of FBI agent Kurt Weller, emblazoned across her back. Jane, Agent Weller and the rest of the FBI quickly realize that each mark on her body is a crime to solve, leading them closer to the truth about her identity and the mysteries to be revealed.")
m6 = Movie.create(title: "Outlander", image: "https://ykvbrw-dm2305.files.1drv.com/y3mNn6yJGWvC5tECWq9Z1mqoaOKKJVzhkQ0VGa0dVE1xgXJ3UB-HHDa0U6cgIqdK6hCPyh6Q2eDF6URNUn5p9FVUBxFVy1MhGdVQ52KoXI_BiZcF88_zFinBKnyu0qZvYWUri4FAYfTkd9rhG6MuxLm_Hcr6RPUtZr3n4KNVb6bYm8?width=242&height=292&cropmode=none", release_year: "2014", plot: "Follows the story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie Fraser, a chivalrous and romantic young Scottish warrior, a passionate relationship is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.")
m7 = Movie.create(title: "Orphan Black", image: "https://wavzrw-dm2305.files.1drv.com/y3m_ycBRmRf4Cr2b88U5mrkpiOtbamVU4n6wwbdQtF0iduEX2b1_2ZnQRVdOlalkLlNzydeMgZFplmJDGvGuSM4J2tht779AOfs5aHA1TR00cZ9rv4p-j2Eb3QRusHo1w78caUq6Aja0rE7SDkHkr7VO7cHoZgkeDdQWmlcRv8XpQ0?width=242&height=292&cropmode=none", release_year: "2013", plot: "“Orphan Black” follows outsider, orphan and street-wise chameleon Sarah. After witnessing a woman’s suicide, Sarah assumes the stranger’s identity, who happens to look just like her. Expecting to solve all her problems by cleaning out the dead woman’s savings, Sarah is instead thrust headlong into a kaleidoscopic mystery as she realizes the dizzying truth: she and the dead woman are clones. As Sarah searches for answers, she discovers the chilling fact that there are more people like her out there - genetically identical individuals who were planted in unsuspecting birth parents and nurtured in completely different circumstances. With no idea who created the clones, she’ll need to discover the reason in a hurry as an assassin is killing them one by one.")

a1 = Actor.create(first_name: "Terrence", last_name: "Howard", image: "https://wqvtrw-dm2305.files.1drv.com/y3moZVJEozrtUuOLGsDeBUdHIqOIPrPW10wpk7-AJelHYjLiUPhRjNesw84b6TKjtnioGK_vC7h8pSr0phfmdEJm90JX_ecxtx3FuRd99CjmRAGRXts5SaZ-7SXAONM_bFC5VjijiRlyH8wxCkSt1cCIan37CnD7A236lXaRJHP-FQ?width=242&height=292&cropmode=none", bio: "Terrence Howard was born in Chicago, Illinois, to Anita Jeanine Williams (née Hawkins) and Tyrone Howard. He was raised in Cleveland, Ohio. His love for acting came naturally, through summers spent with his great-grandmother, New York stage actress Minnie Gentry. He later began his acting career after being discovered on a New York City street by a casting director. Soon, he followed with several notable TV appearances on shows such as Living Single (1993), NYPD Blue (1993) and Soul Food (2000). He became well known for his lead role in the UPN TV series Sparks (1996).")
a2 = Actor.create(first_name: "Bryshere Y.", last_name: "Gray", image: "https://wqverw-dm2305.files.1drv.com/y3mXx8CEcXOamWvMBoy6Ze6_cR0fpJAtbdQIzZMhfVa2GjMv4EUHOIaKtVBNwqkSV6u17XfgSxOuNiLspTzNJmwpY3DgE4VrG6EvrHTjbdoyj_nwlZG-Vo1q0e52TGsDZtyM8jNb8igxzPmeKj2xoo4WRkd5IjJc0OgnDjlC-HTe_4?width=242&height=292&cropmode=none", bio: "Bryshere Y. Gray is an actor, known for Empire (2015), 2015 Billboard Music Awards (2015) and New Edition: The Movie (2017).")
a3 = Actor.create(first_name: "Jussie", last_name: "Smollett", image: "https://wqvyrw-dm2305.files.1drv.com/y3mYzZwSs7-kb86uDPx7a1vbY1LLBvDA2MTLh1u0c-nKgF8yuWl7qfIP7NSefdm5ttRpxsQx1A05PMGfJgGh5a2rh5zXLTKSLIw6-gRszrn3MWVI7VBopvo-iz-IRUE6KMjAAVq4W0rEz8j_uEJFdktLsGAxW480wcYz-8g7OrWXgk?width=242&height=292&cropmode=none", bio: "Jussie Smollett was born on June 21, 1983 in Santa Rosa, California, USA as Jussie Langston Mikha Smollett. He is an actor, known for North (1994), The Mighty Ducks (1992) and The Skinny (2012).")
a4 = Actor.create(first_name: "Taraji P.", last_name: "Henson", image: "https://wqvarw-dm2305.files.1drv.com/y3mXQL9io0jc62P8RvK1nfXAawY7hjD6lLI-vVUnfqtqeVTBpipNFYkFKOAFYq7NRf1ygXlpMAE9TBMuU8EGAF2NdW8p-_bIVd5D0g_booOyuWEni9VbR32KTWhjQB0kqySPyhrVwKpT-OLyJxwNdE_GQlCVmN-djNMyd-5v49EgEo?width=242&height=292&cropmode=none", bio: "Taraji P. Henson was born on September 11, 1970 in Washington, District of Columbia, USA as Taraji Penda Henson. She is an actress, known for Person of Interest (2011), The Curious Case of Benjamin Button (2008) and The Karate Kid (2010).")
a5 = Actor.create(first_name: "Kaitlin", last_name: "Doubleday", image: "https://wqvzrw-dm2305.files.1drv.com/y3mbEbGNdZ-6wdYq2pe_tlH8GYSps9OK88zWZi4RIPoL2szRD5jn0gw3_dtrrBxEl0_-dVrcB7TViwFDInMgxqweK7GPy9-QnXyWsagGDMV2-8VhrCcNV0tmBtTojXV7yDRN044pTNTN255h7bQCAPtJBIRVhX2E_HFFMRiRRsecm8?width=242&height=292&cropmode=none", bio: "Kaitlin Doubleday was born on July 19, 1984 in Los Angeles County, California, USA as Jan Kaitlin Len Doubleday. She is an actress, known for Catch Me If You Can (2002), Waiting... (2005) and Accepted (2006). She has been married to Devin Lucien since May 6, 2016.")
a6 = Actor.create(first_name: "Trai", last_name: "Byers", image: "https://wqvurw-dm2305.files.1drv.com/y3mPeqWUDgvghUrWdRffTq5reEjhTtHlBjXkPyJiRoFFr9tS4_I2qdWiRcWykVh0XTU34zP_iYdxhUC80pZP4ITYrnAca-TXp9aEF9BcJ1s4RBXtrDJkBySoZPoEf3_WTw_D0Nr4Ri1Togq2WgJsjY7nBpU3NYwv1ti0qzNJxUMDj0?width=242&height=292&cropmode=none", bio: "Trai Byers was born on July 19, 1983 in Kansas City, Kansas, USA. He is an actor, known for Empire (2015), Selma (2014) and Americons (2015). He has been married to Grace Gealey since April 14, 2016.")

a7 = Actor.create(first_name: "James", last_name: "Franco", image: "https://xkvurw-dm2305.files.1drv.com/y3mthKYTguq1G7CxPt8vgi7M04m9Cfy_Wn7n4umFZvqMgSWMD7oE9p1W3IzLcUXjRzJWB9yU7kX6NMiFjV8Y0Exs1Xjr2pLKsxLxBU9ZbGSJgmsrvwQHpamn3qLBCX_wHZVAVjfbcsR6qCfxlWxz6rGFstM80zk8vt01YleKqDlUYs?width=242&height=292&cropmode=none", bio: "Known for his breakthrough starring role on Freaks and Geeks (1999), James Franco was born in Palo Alto, California on April 19, 1978. His mother, Betsy Franco, is Jewish, and his father, Douglas Eugene Doug Franco, was of Portuguese and Swedish descent, and ran a Silicon Valley business. James's mother, a writer, has occasionally acted.")
a8 = Actor.create(first_name: "Sarah", last_name: "Gadon", image: "https://w6vcrw-dm2305.files.1drv.com/y3mKJ5l6VZTLIyOF8GkNuVDuaJMPNFpt84MAqYy0NrJSrT0zQNSASDN7ggHibynzoysPEa1PjYKb91M7qB3av_t1LlptDH2zCO1MvIpKZWLs9e621VQjqI5XT-ZZVayby00SNiohHyPdyXpJlZMU6mX7lucrmwygWBvW6Ixkn_LwWg?width=242&height=292&cropmode=none", bio: "Sarah Gadon was born in a quiet residential area in Toronto, Ontario, to a teacher mother and a psychologist father. She grew up with the support and encouragement of her parents and older brother James and with this was inspired to reach her limits in acting and dance alike.")
a9 = Actor.create(first_name: "Lucy", last_name: "Fry", image: "https://w6vbrw-dm2305.files.1drv.com/y3meVga1XMu_E-vqqQUIzm3uWazR-i83jhkgwkPKe6-7yJcSaDRLTjVMFyT2_RXmOqS2RoLhd_0t2HUoKlb2ja-uAaGHWi51VTyWZBIB_B1z_GxLXkmijIognZfHZiqeJ0J-jtE0uiDKOB815_fZtWp8YnN-n5OH5qOzuliWUOeWYI?width=242&height=292&cropmode=none", bio: "Lucy Fry was born as Lucy Elizabeth Fry. She is an actress, known for Vampire Academy (2014), Mako Mermaids (2013) and Now Add Honey (2015).")
a10 = Actor.create(first_name: "Daniel", last_name: "Webber", image: "https://xkvarw-dm2305.files.1drv.com/y3mtLn1N0TVC4nXZF-dndUKkUCyQszHCYjNk9e2e_yXjT1x6QFZe-c6vFhgPDbSH96mdRRTYK0MyXcVFuZOxljJTcgnY65jAJQCE3ADVF9CHJPwbBziwvyj0OsuZTTpzPSsVZNxLqnmX6L37FaYdfWhS2Hmc1YtnrLQkGtRKmR-U9Q?width=242&height=292&cropmode=none", bio: "Daniel (Peter) Webber was born on the 28th of June, 1988 in the city of Gosford, New South Wales, Australia. His mother's name is Vick Webber, his father is Peter Webber, who ran a Tree Removal company for 20 years. He has an older sister Kylie Webber and a younger sister Sarah Webber. Daniel first came to notice in David Fields controversial film The Combination, after auditioning and acquiring the role of a Jason by himself. Due to his work on the Combination he signed with an agency and worked in the acclaimed TV drama All Saints. His breakthrough however came playing Darius in Bob Baker's Doctor Who spin off series, K9. Daniel worked opposite Emily Browning in Julia Leigh's haunting erotic fairytale, Sleeping Beauty in 2011.")

a11 = Actor.create(first_name: "Maeve", last_name: "Dermody", image: "https://w6vxrw-dm2305.files.1drv.com/y3mgNo3D8FmKtgZEcTM8AeFGLWWN2NwvQKt0vA-THjAiVsP30Dajcg3zCQfUzJSeb66kkgDAFVk0_VmdC2ZVFodr8bOioUXojebhe7CAuzov6QoXJis3xhOZC82Ep2EPddbNdSQeQqTV7ly8GoobSGhNaCebV3V0JQOmbNN0xWT690?width=242&height=292&cropmode=none", bio: "Australian actress Maeve Dermody is the daughter of Susan Murphy Dermody, a film theorist, historian, and director. Her father is a psychologist. Dermody's family encouraged a love of literature and the arts, and supported performing as well - her mother gave the 5-year-old a part in her film Breathing Under Water (1993).")
a12 = Actor.create(first_name: "Miranda", last_name: "Richardson", image: "https://w6vyrw-dm2305.files.1drv.com/y3mPJ63S9Xoj8Tfbg8vxxBemFICf-6TF64qFzgPue92tiH4o16LojewVBV14ZhkZ8GucGODklftF1yQHctqRAPcvGUuHWNM3e0X2mKeGYN411u7ZVks5MIAoEuFtyQ1hZJhhCZr8EWldmiCFlLq7Dz_LqJ-tbz-20PwLKqdJoPfsB8?width=242&height=292&cropmode=none", bio: "Miranda Richardson was born in Southport, Lancashire, England on March 3, 1958, to Marian Georgina (Townsend) and William Alan Richardson, a marketing executive. She has one sister, eight years her senior. Her parents and sister are not involved in the performing arts. At an early age she performed in school plays, having shown a talent and desire to turn herself into other people. She has referred to it as an emotional fusion; you think yourself into them. This mimicry could be of school friends or film stars. She left school (Southport High School for Girls) at the age of 17, and originally intended becoming a vet. She also considered studying English literature in college, but decided to concentrate on drama and enrolled at the Bristol Old Vic Theatre School (as did many well-known British actors). After three years she graduated and moved into repertory theatre. She became affiliated with the Library Theatre in Manchester in 1979, where she became an assistant stage manager. She obtained her Equity card, and after several regional productions, first appeared on the London stage (Moving at Queens Theatre) in 1981. British television roles soon followed, and then film. Since then, Miranda has moved into the international arena, and has made films in America, France and Spain. Television work (on both sides of the Atlantic) continues, as does some stage work. Her roles are diverse, but powerful and engaging.")
a13 = Actor.create(first_name: "Toby", last_name: "Stephens", image: "https://w6vzrw-dm2305.files.1drv.com/y3muBEO_hkcJhhdd0FanuH4DG_s-mtJGjK8_8v3u2C6ZyR9mAPY61-AMvRmFNU6ezYpwHWrSji4APnPKzIiSsqSzr9_LPFVwAj9BpW5NWdaZJO9yotPX_h4RdeA2I_1e_PzYU4vwno0xgeiUdBf5fky-7iYTT-1j59m9OPwbbLoGLU?width=242&height=292&cropmode=none", bio: "Toby Stephens began his acting career while a stagehand at the Chichester Festival Theatre, in end-of-season productions mounted by the crew. In his brief professional career, he has already won the Sir John Gielgud Prize for Best Actor and the Ian Charleson Award for his performance in the title role of Coriolanus at the Royal Shakespeare Company in 1994. His other work at the RSC includes Measure for Measure, A Midsummer Night's Dream, Antony and Cleopatra, Wallenstein, All's Well That Ends Well and Unfinished Business. Stephens also starred in Peter Hall's production of Tartuffe at the Aldwych Theatre and has just finished filming The Tenant of Wildfell Hall (1996). His television appearances include A View from the Bridge (2012) and The Camomile Lawn (1992). He made his screen debut in Sally Potter's Orlando (1992).")
a14 = Actor.create(first_name: "Charles", last_name: "Dance", image: "https://w6verw-dm2305.files.1drv.com/y3mpq6dYAQWIT9sMth3vmP_knjs1fmUgXyktWJAnKD5I4boGb0uXpLPlpfz-sy2TOlLYdtwx4L6OEyapCBPiwLKv1ws5d8Gkmqje2o-mQDTSQ74iZ_y_XYS3dKX_itZ_pfc4PDca6I2kM0LSSuNF6JKW4zJ_-EdmXL_cicXmV0XsYI?width=242&height=292&cropmode=none", bio: "Charles Dance was born on October 10, 1946 in Redditch, Worcestershire, England as Walter Charles Dance. He is an actor and director, known for The Imitation Game (2014), Alien³ (1992) and Last Action Hero (1993). He was previously married to Joanna Haythorn.")

a15 = Actor.create(first_name: "Melissa", last_name: "Benoist", image: "https://xkvyrw-dm2305.files.1drv.com/y3muun99aMpevuMnd-LPsRzp4qdAZexl_7_8M8YbG7IQde5Ah8gRYv0OKaSYbjS9jTsZW3ykvIc_gcnK5o_cZFfYi5V3RQUlwvufApbpYSlmKwpkSgXXB_ni6-hytsIQbTecNVPIy8HSwlWVfsfgxz-d_SuW4-r36OjhQaXoFcfo1Q?width=242&height=292&cropmode=none", bio: "Melissa Marie Benoist is an American actress and singer, known for her portrayal of \"Marley Rose\" on Season Four and the start of Season Five on the Fox musical comedy-drama television series Glee (2009). Aside from her role on \"Glee\", she has appeared in a number of television series, including Homeland (2011), The Good Wife (2009) and \"Law & Order\". Benoist's first film was in singer Mariah Carey's Tennessee (2008). She appeared in director Damien Chazelle's film Whiplash (2014), which won top prizes (Grand Jury and Audience awards) at the Sundance Film Festival in Park City, Utah, in January 2014.")
a16 = Actor.create(first_name: "Mehcad", last_name: "Brooks", image: "https://xkvxrw-dm2305.files.1drv.com/y3miA7J28ibI8VpRCHmNVSM6gVXMcn1A2IeO4noi92CoBS_1cDTTFo4bBOekA3CTV8GU69oA3vPfdblFfGI3nj4aCDASJF-2KdB7UJN2ZNG2umMN1Hb6NqdjTLtSrPDc3PiXqxyVykxvMIrvtPM7PgPY0YdqYsZZ7C2BpKouuwTSuQ?width=242&height=292&cropmode=none", bio: "Mehcad Brooks continues to rise as one of Hollywood's most promising stars. Brooks was in USA's new drama Necessary Roughness (2011), in which he portrayed Terrence \"TK\" King, the star wide receiver for the Hawks who is becoming notorious for his frequent fumbles -- not to mention his regular run-ins with the law. He is forced into counseling which becomes the key that unlocks his troubled past and helps him on the path to healing.")
a17 = Actor.create(first_name: "Chyler", last_name: "Leigh", image: "https://xkvcrw-dm2305.files.1drv.com/y3mqlfTMBmGnjT3jPDiR24HXH4DJA895I_13PSjP_gq74GX5L6TOMNypf19BdCyQkUBkVYkREthbSN-a4tn12GsVnjQB4Q9uCzxw1HHdNbTttNYyMiw-sizBVQOIwIE4oVdWu-G4l7WXkU11fgVieH81zaPlIdenmIeCKXDzqMr_B8?width=242&height=292&cropmode=none", bio: "Born in Charlotte, North Carolina and raised in Virginia Beach and Miami Beach, Chyler began her career in front of the camera at age 12 modeling for magazines and catalogues. Her success in print later led to national commercials for Coca Cola and Wendy's, among others. By age 16, she had already completed several pilots (ABC's Wilder Days (2000) and the WB's Saving Graces (1999)) at the onset. Aaron Spelling confirmed the young actress's talent when he hired her a few years ago as a series regular in the WB series Safe Harbor (1999) after seeing her performance on Saving Graces (1999). She also guest-starred on 7th Heaven (1996) in a powerful three-story arc wherein her character, \"Frankie\", a young, inept mother had adversely influenced the family.")
a18 = Actor.create(first_name: "Jeremy", last_name: "Jordan", image: "https://xkverw-dm2305.files.1drv.com/y3mLdmXd0lmlPOEeSbAllqJSv9NcF0Yow1tMce_1BVUkGDSE55qD7kJ7HJxQchbIDMAF6-q7RSLXc7BmWSKImEQ-tgmOAN0rGEHphjEOkVSwyNBqlaPbX1KftYMFks9d3iq145Yi-vep-HOzsp92A-jr9bsLLcbwOCZGWJDkAipwUU?width=242&height=292&cropmode=none", bio: "Jeremy Michael Jordan was born and raised in Corpus Christi, Texas. He is most well-known for his television roles in Supergirl (2015) and Smash (2012). Jeremy graduated in 2007 with a degree in Musical Theatre from Ithaca College. Soon after, he landed his first Broadway role in \"Rock of Ages.\" In December of 2009, he left the show to play Tony in Broadway's \"West Side Story.\" In 2011, Jeremy originated the role Clyde Barrow opposite Laura Osnes in the new musical, \"Bonnie & Clyde,\" a performance which earned him the Theatre World Award. Later that season, Jeremy went on to star in the world premiere production of Disney's \"Newsies\" on Broadway. He received Tony and Grammy Award nominations for his role as Jack Kelly. Four months into the run, Jordan landed the role of Jimmy Collins in season 2 of \"Smash.\" For a few months, he would film the series by day, while continuing to star in \"Newsies\" in the evenings. Jeremy soon left \"Newsies\" to film \"Smash\" full-time.")
a19 = Actor.create(first_name: "David", last_name: "Harewood", image: "https://xkvdrw-dm2305.files.1drv.com/y3m9TL58AVC8joNMmr4Lt_EWoRzlVITVL1lSeepW_1qq30JhUjo59nIeWRq90zHMpv_LvFDpb6K1WMIBxcxgEjcAm-Xe9CBjweQ17brvDgrfyXPwZln1TaVhRcvdwg2zdXFWiD32XJmJmgwEmFEvybgrvp8iMRzBheu6bo5TgpEVHU?width=242&height=292&cropmode=none", bio: "David Harewood was born on December 8, 1965 in Birmingham, England. He is an actor, known for Kim Cuong Mau (2006), Homeland (2011) and The Merchant of Venice (2004). He has been married to Kirsty Handy since February 26, 2013. They have two children.")
a20 = Actor.create(first_name: "Calista", last_name: "Flockhart", image: "https://xkvbrw-dm2305.files.1drv.com/y3mBBaoP25V6e2zMUoZPsqb5QY3jv1QVF_FJaZPobxC2PpURSRDaChHll0egX7WA6jk_JL7CDrh0YPzWThT__FnLJclwzqNrKwI1HoNIqtTAyl98q6bCqqk0JBXs137O47OqOKCR_DJEZQTIoDu9HSg37Xbgb4QghTPZBtICTsNxiw?width=242&height=292&cropmode=none", bio: "Calista Kay Flockhart was born 11 November, 1964 in Freeport, Illinois. Her mother, Kay (Honohan), was a school teacher, and her father, Ronald Flockhart, worked for Kraft Foods Inc. She has Irish, Scottish, German, and English ancestry. Calista was named after two of her great-grandmothers, who both had the middle name \"Calista\". Flockhart attended Rutgers University in New Jersey to study acting. After college, she worked in regional theatre in Cleveland, Louisville, Chicago and Houston for $400 for eight weeks of work. In 1994, she got her first Broadway role playing \"Laura\" in Tennessee Williams' \"The Glass Menagerie\", for which she was recognized with the Theater World and Clarence Darwent Awards. She's also played in an all-star production of Anton Chekhov's \"The Three Sisters\" playing \"Natasha\". She wasn't too fond of TV before Ally McBeal (1997), but did take part in a 1992 episode of the HBO series Lifestories: Families in Crisis (1992). She did take part in many movies, but among them is the remake of The Birdcage (1996). Calista played the fiancée of Robin Williams's son. In 1997, she appeared in Telling Lies in America (1997) as the object of Brad Renfro's obsession.")

a21 = Actor.create(first_name: "Sullivan", last_name: "Stapleton", image: "https://wqvdrw-dm2305.files.1drv.com/y3mz54YR78d8WvRSmSF9dp4ut_PdqVieeNkUUVbJ6X6Y8d2lr7DgzRZkWMAZzIH3hkkEeXFs6EMnI2VXHV8tIuSKwHqwkNi1gf2Xy9S1U7rVlRlszCWZGyD0_clZ4SCxcm0O7wGt5FM3u4NrkpWGOc9Woua7O60weJIYGb5N2cFZZw?width=242&height=292&cropmode=none", bio: "Sullivan Stapleton was born on June 14, 1977 in Melbourne, Victoria, Australia. He is an actor and producer, known for 300: Rise of an Empire (2014), Animal Kingdom (2010) and Strike Back (2010)")
a22 = Actor.create(first_name: "Jaimie", last_name: "Alexander", image: "https://wqvbrw-dm2305.files.1drv.com/y3mHdZiy8VdBY1uGqEpAE0NMY6g1Bz6i5_a9VZCrFWbQNJZn4NKwnJ8Lxp0qscK5DMNH7gvy9Xi_jsPyCb2FAaUMJhJ1Q7ZiLI-QLnS4R0rsEVVbsyBGS3x6M3Qdtbfi2DczGNfLackukmeS7Zcw2TqEWpoGgsPllOBLq0XXDUQfBs?width=242&height=292&cropmode=none", bio: "Jaimie Alexander was born in Greenville, South Carolina, but moved with her family to Grapevine, Texas, when she was four years old. She took theatre classes in grade school as a hobby but was kicked out in high school because she could not sing, and so she took up sports instead. At age 17 she substituted for a friend at a meeting with a scouting agency and she met her manager, Randy James, who sent her some scripts. After graduating from high school she moved to Los Angeles, California, to pursue acting.")
a23 = Actor.create(first_name: "Rob", last_name: "Brown", image: "https://wqvcrw-dm2305.files.1drv.com/y3mFqiTDTt9AnXhTKeZIiCkTY6hG2K_FUc_wgqsO0JBZqSEB4WKWXvkVb_OO0DyerLriWtA4bhhXAZiCF-L9TvwEIVLHFL-76Ib4RY4UygWFm49Xx2CxfynPah3yQ2khkq-95ANbLt2_R3qV4M_JhiQdASAyzmPsy_ytpk_jFoE6tg?width=242&height=292&cropmode=none", bio: "Rob Brown was born in Harlem and raised in Brooklyn, New York. A natural who never studied acting and who had no professional acting experience, made his acting and motion picture debut in Finding Forrester (2000). Rob celebrated his 16th birthday just before the start of production. He is a talented athlete in high school playing both basketball and football.")
a24 = Actor.create(first_name: "Audrey", last_name: "Esparza", image: "https://w6vtrw-dm2305.files.1drv.com/y3m6zl3_Lnjta7bTZK63og_OhBzMiqSNVb6fEidvpQfB4Hyq7eTu4vQ2WsGrr1PGaJsP2UzOFyRAyv_8cIumXOSScVuDTTRp251IFs6kx4Wq0wY4rT79Vfo98oB-SfRdvdmJVtKurzABh-FmPJkh-4GhO3_5ppNOBTh8kcLP_OFPjY?width=242&height=292&cropmode=none", bio: "Audrey Esparza is an actress, known for Blindspot (2015), Floating Sunflowers (2014) and Amateurs (2013).")
a25 = Actor.create(first_name: "Ashley", last_name: "Johnson", image: "https://w6varw-dm2305.files.1drv.com/y3mT8c0TMJ8ks76gDJwG01vhXaI9K1etUgqqBAKfZeoUigGcZrGj8c8m8V2t6zFj0PYuTRrADYKzQBOCq0Zhadrn3bUjKQunmDxNulqkGnqIa802CKw5cTbZI_Lke3g5aELRHoqrxU1loE3aQEzlLI8vmcwklK-KSsOASbNdg2WnPU?width=242&height=292&cropmode=none", bio: "Ashley was born in Camarillo, California on August 9, 1983, to Cliff and Nancy Johnson. When she was 9 days old, her family packed up and moved to Michigan where her father was transferred (Ship captain of an exploration ship). They finally ended up moving to \"The Town That Time Forgot\" called Franklin.")

a26 = Actor.create(first_name: "Caitriona", last_name: "Balfe", image: "https://wavtrw-dm2305.files.1drv.com/y3mCRN9rgWzId0Bnm8mhl6uTkoo-VmLHQoRhajQ5LpkD4bjAkygmTgs_tK9Wyb7Z4kGfTq5l-8bWDeHneh580WseYjj2jTCOsUYT-VcQi3Jf-7iVhSb6PTw9kfJkHFE_NS0ZDmgpvpjV5mBjH6U2QN-qO6QQdteMVicK1BsJ_YfZEY?width=242&height=292&cropmode=none", bio: "Caitriona Balfe was born in Dublin, Ireland, and grew up in the village of Tydavnet, in County Monaghan. She started modeling at the age of 19 after she was scouted by an agent while she was collecting money for charity at a local mall. She has both walked the runway and been featured in advertising campaigns for many top fashion brands, including: Dolce & Gabbana, Fendi, DKNY, Burberry, Dior, Louis Vuitton, H&M, Marc Jacobs, Valentino, Cacharel, Roberto Cavalli, Givenchy, Hugo Boss, Armani, Dries van Noten, Calvin Klein and Chanel.")
a27 = Actor.create(first_name: "Sam", last_name: "Heughan", image: "https://ykvcrw-dm2305.files.1drv.com/y3mnzCUM_A70iSwUK-UDEev4rhIhDMqvXI5ucaDRXpsqc-DZFLeKbIIjAbcmUcnxY13L1AHuYUrweuU4dyKoG0rfxE006mLZ9NCKki3HHY_wtBH5IPGz_spQ2t6jJE4k3rXh_8cSJ6hJ_cOEKCTpAPyYAPoGcczlF1yPr3I25CM07A?width=242&height=292&cropmode=none", bio: "Sam Heughan was born April 30, 1980 in New Galloway, Dumfries and Galloway, Scotland. An accomplished stage and screen actor best known for Outlander (2014), A Princess for Christmas (2011), and A Very British Sex Scandal (2007). He is an active patron of Youth Theatre Arts Scotland and Leukemia and Lymphoma Research. He attended the Royal Scottish Academy of Music and Drama (now the Royal Conservatoire of Scotland) located in Glasgow, Scotland.")
a28 = Actor.create(first_name: "Tobias", last_name: "Menzies", image: "https://ykvdrw-dm2305.files.1drv.com/y3m5VfZ5mwWh_K4rURl2dx3ZcDXrl0Mk0os43lKGF2Ce4wNw6zpTyfe2DZ7goiUewz7gFwUhbkiyv0m4TwiUoGaNoM5_Or6rkc_uxCsQ0FxXB2C5YuPfd1vNj0GpWc8wgZ6ImCEbOu_FqubbHDe9TW3ogNed8oHqe0MY8Urp3WFOL8?width=242&height=292&cropmode=none", bio: "Tobias was born in London. He graduated from the Royal Academy of Dramatic Art (RADA) in 1998 and began his acting career in popular UK series such as Foyle's War, Midsomer Murders, and Casualty. He also appeared in the controversial drama A Very Social Secretary. He is best known to international audiences as Marcus Junius Brutus in the television series Rome.")
a29 = Actor.create(first_name: "Duncan", last_name: "Lacroix", image: "https://wavurw-dm2305.files.1drv.com/y3mgcMuPaN8iSrbEg3QGmA41g01xjz83-N_5QW-TZs-U31gtQujRA4T98wGRrRDZ3e2235jZHFLvoShjhm6d2Dr60yNLQxol7MtJDDHsABWIftKRhMpv-QrZ54WB7b2U29HBXLOt2UVfEajm-CmWD1J_ZsIuXvOZx8iiu-0okkMK-g?width=242&height=292&cropmode=none", bio: "Duncan Lacroix is an actor, known for Outlander (2014), A Terrible Beauty... (2013) and Vikings (2013).")

a30 = Actor.create(first_name: "Tatiana", last_name: "Maslany", image: "https://wavarw-dm2305.files.1drv.com/y3md8nHEPU5KiVIia1lJfy8FW24RdK1hvdJqX6g1Q2rkmums9x-fvTlRQoajyOzGOWAHVII8Mbu8rOGx1RhSGzu22VkY_FVCsK0r0JXksmhezr_mVc0KQsfBFTeyseM3mxw7dyP3GazobFzW0XqplRmLB9WhRh2QqeCMJ4JiWBalZU?width=242&height=292&cropmode=none", bio: "Tatiana Gabrielle Maslany was born September 22, 1985 in Regina, Saskatchewan, to Renate, a translator, and Dan, a woodworker. She graduated from Dr. Martin LeBoldus High school in 2003. She was a well respected student, and participated as often as possible in school productions. She is well known for her participation in the Canadian Improv Games. Maslany starred in the 2006 television movie, Booky Makes Her Mark (2006) along with Megan Follows and Stuart Hughes.")
a31 = Actor.create(first_name: "Jordan", last_name: "Gavaris", image: "https://waverw-dm2305.files.1drv.com/y3m6ySQfzGjU0ym_XBZ8J-0ZBp_H7F8r43i42I95DNst0Ilv8N_OKAAJAKdh8zzv3-uldGJvj6mS7gthqdmLY5Nz0RZwkndAz5N0x8AEAxQr-R5yxYJDPVj-7WbUlAD-X1oYWeVQnQefehjymsmD-b8pLWjBhBez0eTp_cxkskGD80?width=242&height=292&cropmode=none", bio: "Jordan Gavaris was born on September 25, 1989 in Brampton, Ontario, Canada as Jordan James Gavaris. He is an actor, known for Hoan Vi (2013), Curse of Chucky (2013) and 45 R.P.M. (2008).")
a32 = Actor.create(first_name: "Maria", last_name: "Kennedy", image: "https://wavyrw-dm2305.files.1drv.com/y3mA7xqzYnJv2WXFXrRElEYhTum_SE0zDzFo7wK6r6ONTlAWApr7VqgqsENN404E01yM6wbVA7XnHRGIBb404IKZAq8YlOa4GEI0H7vLeRwTQFwjExcUubIrEx3uheODb3XTj-BKalpi9q_-_wM5WQsgo5-RKliCRrcgPCAIAmYTrM?width=242&height=292&cropmode=none", bio: "Maria Doyle Kennedy was born on September 25, 1964 in Clontarf, Dublin, Ireland as Maria Josephine Doyle. She is an actress, known for Jupiter Ascending (2015), The Commitments (1991) and Albert Nobbs (2011). She has been married to Kieran Kennedy since 1988. They have four children.")
a33 = Actor.create(first_name: "Kristian", last_name: "Bruun", image: "https://wavxrw-dm2305.files.1drv.com/y3mNUno3G-HEoowWUsQ4Tmqh-N4RM6kV2Yy6QYyNywOVOO2QsS24KJy-0eZz7tpBpcLLf9ubhBMZRFSRfs-EwHhbvrVN0hkQeftKWqCGIYViSg_SW7i3QoqRZZJvfG9o-CQbtixgOs99Hn01XoNmsyH8V49LX2rv_bppJOdI_XS7Jk?width=242&height=292&cropmode=none", bio: "Kristian Bruun was born and raised in Toronto. He attended Valley Forge Military Academy in Pennsylvania, Queen's University in Ontario and the George Brown Theater School in Toronto. He has lived and worked in Germany and the UK, and has performed in theaters across Canada.")
a34 = Actor.create(first_name: "Dylan", last_name: "Bruce", image: "https://wavbrw-dm2305.files.1drv.com/y3m4coKhWYSHeg95zjZ2VHSpFVlW_VadIvD7oJIQsgtLpp8wFQyaNzhoR9GkDfNCtsad9h0TsxH-0KYHjiNSZ2S8fOVYEIGHAxZ0KaUpRF6-VlLv9z-vfyINMSjHXgjxzJPQfgUnLuGCNtTpIAzbK-kM7KmSaHhSUkHtzYzfR50WQg?width=242&height=292&cropmode=none", bio: "Dylan Bruce has established himself well in television. Bruce was born in Vancouver, Canada on April 21, 1980, and raised in both Vancouver and Seattle, Washington. In 2005 Bruce appeared on the mini-series 24: Conspiracy (2005), the spin-off to the original Kiefer Sutherland series 24 (2001).")
a35 = Actor.create(first_name: "Evelyne", last_name: "Brochu", image: "https://wavcrw-dm2305.files.1drv.com/y3mjzZis62lXxuw_85KJhO913_4SG9kyTbNpPo5waQGTqvm-OansNi65UrQN-qE66tjNfYkxyTsCm8SxO6UPCogamP2dcl5GRr_NAcczbilq9fHFMcRKXM_ztsepW0puNjm_Snk4yPwd75sze91ngP8ZNHz00RhyYJB5_-gH_T8pdU?width=242&height=292&cropmode=none", bio: "Evelyne Brochu was born in 1983 in Quebec, Canada. She is an actress, known for Inch'Allah (2012), Café de Flore (2011) and Tom at the Farm (2013).")
a36 = Actor.create(first_name: "Kevin", last_name: "Hanchard", image: "https://wavdrw-dm2305.files.1drv.com/y3miNBoPa5VC1jrdtceU8scYjknLE9ZyCKKN0dMyx-NpMl0XK83jBPdem6AyBFSZ-oBgxSdex-TrkCUtN1IA8mpoTPBVlPtMot4dwYhHwv1iHTAwndClJHZS9dXfY9lM8tE2VetHcN8L-ODQkl2h9kNNYWAEG7Adf4AcQNODDSv9O8?width=242&height=292&cropmode=none", bio: "Kevin Hanchard is a veteran actor who, in recent years has become one of the nation's most sought after performers. Although no stranger to film and television, this dynamic and versatile actor has made his name in the world of theatre. His knack for bringing a degree of humanity to flawed characters has become the hallmark of his career to date.")

aS01E01_m7 = Episode.create(ep_number: "S01E01", ep_title: "Natural Selection ", ep_plot: "Sarah Manning witnesses the death of a woman who looks exactly like her. She decides to escape her dramatic life and take the woman's identity for her own. But converting to a new life is harder than she expected.", ep_time: "09:00" ,ep_date: "2013-03-31", ep_broadcast: "BBC America")
aS01E02_m7 = Episode.create(ep_number: "S01E02", ep_title: "Instinct ", ep_plot: "Sarah looks deeper into the secret life that Beth seems to have lead. Art refuses to return Beth's money until Sarah goes through with the hearing.", ep_time: "09:00" ,ep_date: "2013-04-07", ep_broadcast: "BBC America")
aS01E03_m7 = Episode.create(ep_number: "S01E03", ep_title: "Conditions of Existence ", ep_plot: "Sarah has reinstated Beth into the detective force just as law enforcement finds Katja Obinger's body.", ep_time: "09:00" ,ep_date: "2013-04-14", ep_broadcast: "BBC America")
aS01E04_m7 = Episode.create(ep_number: "S01E04", ep_title: "Effects of External Conditions ", ep_plot: "While Sarah tries to track down her mysterious blonde clone, Alison fills in for Sarah on a visit to see her daughter.", ep_time: "09:00" ,ep_date: "2013-04-21", ep_broadcast: "BBC America")
aS01E05_m7 = Episode.create(ep_number: "S01E05", ep_title: "Conditions of Existence ", ep_plot: "Both Sarah and Alison believe that their lovers are actually monitoring them. Vic finds out that Sarah's alive.", ep_time: "09:00" ,ep_date: "2013-04-28", ep_broadcast: "BBC America")
aS01E06_m7 = Episode.create(ep_number: "S01E06", ep_title: "Variations Under Domestication ", ep_plot: "Sarah's hunt for answers is interrupted by a trip to the suburbs. Alison's paranoia has boiled over, putting all the Orphans at risk. But when Sarah, Alison and Beth's worlds dangerously collide, Sarah must decide who to trust with her secret.", ep_time: "09:00" ,ep_date: "2013-05-05", ep_broadcast: "BBC America")
aS01E07_m7 = Episode.create(ep_number: "S01E07", ep_title: "Parts Developed in an Unusual Manner ", ep_plot: "With Paul missing, Sarah is forced to confront the conspiracy head on. But when Paul learns Sarah has kept essential information from him, the fragile trust between them threatens to shatter. Meanwhile, Cosima grows closer to Delphine and the dangerously fascinating Dr. Leekie.", ep_time: "09:00" ,ep_date: "2013-05-12", ep_broadcast: "BBC America")
aS01E08_m7 = Episode.create(ep_number: "S01E08", ep_title: "Entangled Bank ", ep_plot: "Art and Angela investigate Sarah's life. Alison has an affair with her best friend's husband. Paul ties up a loose end. Helena finds Sarah's weak spot.", ep_time: "09:00" ,ep_date: "2013-05-19", ep_broadcast: "BBC America")
aS01E09_m7 = Episode.create(ep_number: "S01E09", ep_title: "Unconscious Selection ", ep_plot: "After Kira's life is threatened, Sarah is on the warpath, but Dr. Leekie makes her think twice about her plans for revenge. Meanwhile, Cosima faces the truth about Delphine, forcing her to choose sides. Now, it's up to Sarah to decide the killer's fate, but the truth about where Sarah came from changes everything.", ep_time: "09:00" ,ep_date: "2013-05-26", ep_broadcast: "BBC America")
aS01E10_m7 = Episode.create(ep_number: "S01E10", ep_title: "Endless Forms Most Beautiful ", ep_plot: "Dr. Leekie offers deals to both Alison and Cosima. Sarah meets Rachel Duncan. Delphine tries to make amends. Alison tries to get her life back together. Helena escapes.", ep_time: "09:00" ,ep_date: "2013-06-02", ep_broadcast: "BBC America")

aS02E01_m7 = Episode.create(ep_number: "S02E01", ep_title: "Nature Under Constraint and Vexed ", ep_plot: "Rachel has kidnapped Kira and Mrs. S. While trying to elude Rachel's thugs herself, Sarah has to decide whether to trust Paul as the person who has the best access to Rachel of those she knows in order to get Kira back. All Paul does tell Sarah is that there is a black tie event at Dyad at which Rachel will be in attendance. Sarah decides that she needs to attend the event - Cosima who already is an invitee - but has no plan beyond knowing that she will need to get in there with concealed gun in hand. With this scant outline of a plan, Sarah enlists the help of Felix ...", ep_time: "09:00" ,ep_date: "2014-04-20", ep_broadcast: "BBC America")
aS02E02_m7 = Episode.create(ep_number: "S02E02", ep_title: "Governed By Sound Reason and True Religion ", ep_plot: "On information from Art, Sarah learns that it is not Rachel who abducted Kira, but rather the Prolethians, the reasons she does not know behind the abduction. However, there is no news whatsoever about Mrs. S, who she believes must have also been abducted along with Kira, which is only of little concern to her based on what her birth mother told her before her death. Regardless, Sarah decides to trust Art so that he can help her locate Kira. What Sarah discovers in the matter is not quite what she expects, which results in her not knowing who to trust. Art also tries ...", ep_time: "09:00" ,ep_date: "2014-04-27", ep_broadcast: "BBC America")
aS02E03_m7 = Episode.create(ep_number: "S02E03", ep_title: "Mingling Its Own Nature with It ", ep_plot: "Sarah is able to escape with Kira from the bird watchers and Mrs. S, and now, along with Felix, are on the run with no money. They decide to take refuge at a secluded house where the owner seems to be away. But the choice of the house is no accident. This stop has an unintended effect on Felix. As Alison prepares for opening night, she slowly begins to unravel under all the pressure, which includes meeting someone who she believes is another monitor. Cosima learns from Delphine of yet another clone, Jennifer, who recently died from whatever ails Cosima herself. They ...", ep_time: "09:00" ,ep_date: "2014-05-04", ep_broadcast: "BBC America")
aS02E04_m7 = Episode.create(ep_number: "S02E04", ep_title: "Governed As It Were By Chance ", ep_plot: "Sarah survives the car crash, is quickly reunited with Kira and sets off with Cal in his camper. She decides to head back to the city to find out from Mrs. S just what is going on. She also pays a visit to Rachel which doesn't quite go as expected. At the Dyad Institute, Cosima takes on the task of finding out about Project Leda. Alison awakens from her drug and alcohol stupor to find her right arm in a sling - and that she's in a rehab clinic. Felix convinces her she should spend a week there and just rest. Henrik Johanssen makes it clear to his daughter Gracie that ...", ep_time: "09:00" ,ep_date: "2014-05-11", ep_broadcast: "BBC America")
aS02E05_m7 = Episode.create(ep_number: "S02E05", ep_title: "Ipsa Scientia Potestas Est ", ep_plot: "Rachel returns home to find Rosen dead, which she takes out on Sarah and Cosima. She also makes Paul an offer he can't refuse, even if he wanted to. In this new position, Paul decides to use Felix to help Rachel. Leekie, unlike Rachel, shows that his plans veer toward the truly scientific, he who provides Cosima and Delphine with some information about the clones' past. Feeling indebted to Helena for saving her from Rosen, Sarah decides to help Helena within the bounds of what Sarah believes is right. Helena may have thoughts of her own about what she wants to achieve...", ep_time: "09:00" ,ep_date: "2014-05-18", ep_broadcast: "BBC America")
aS02E06_m7 = Episode.create(ep_number: "S02E06", ep_title: "To Hound Nature in Her Wanderings ", ep_plot: "Sarah and Helena are traveling together to Cold River to find out more about their clone past and specifically the person who Helena refers to as the Swan Man. This trip marks the first time that Helena has felt a sense of freedom in a long time. This freedom, however, may ultimately cause problems for her. Sarah's quest for information takes her to some unlikely places, or more precisely to some unexpected people. She gets some help in this quest by Art and Felix, who have the information obtained from Maggie Chen's storage unit. Felix, however, is often in a state ...", ep_time: "09:00" ,ep_date: "2014-05-25", ep_broadcast: "BBC America")
aS02E07_m7 = Episode.create(ep_number: "S02E07", ep_title: "Knowledge of Causes, and Secret Motion of Things ", ep_plot: "When a rehab confidante betrays Alison and threatens to expose the truth about Aynsley's death, she goes into free fall on the eve of Family Day. With Donnie and the kids set to visit, it's all clones on deck to contain the fallout.", ep_time: "09:00" ,ep_date: "2014-06-01", ep_broadcast: "BBC America")
aS02E08_m7 = Episode.create(ep_number: "S02E08", ep_title: "Variable and Full of Perturbation ", ep_plot: "A new player in the clone conspiracy turns up at Felix's door, sending him into crisis mode. With Cosima running out of options, Sarah struggles with the decision to surrender a crucial piece of leverage and make a deal with DYAD.", ep_time: "09:00" ,ep_date: "2014-06-08", ep_broadcast: "BBC America")
aS02E09_m7 = Episode.create(ep_number: "S02E09", ep_title: "Things Which Have Never Yet Been Done ", ep_plot: "Cosima takes a turn for the worse, forcing Sarah to take desperate action - with tragic consequences for those she loves. The Proletheans set their ultimate plan in motion. Alison and Donnie tangle with the law.", ep_time: "09:00" ,ep_date: "2014-06-15", ep_broadcast: "BBC America")
aS02E10_m7 = Episode.create(ep_number: "S02E10", ep_title: "By Means Which Have Never Yet Been Tried ", ep_plot: "After the successful abduction of Kira, Sarah prepares to surrender to Rachel and the Dyad Group; but the Clone Club has other ideas as they band together to pull off the ultimate rescue.", ep_time: "09:00" ,ep_date: "2014-06-22", ep_broadcast: "BBC America")

aS03E01_m7 = Episode.create(ep_number: "S03E01", ep_title: "The Weight of This Combination ", ep_plot: "Sarah pursues the missing Helena who is held in a faraway compound. Sarah must use her wiles - and acting chops - to deter a Topside investigator who threatens the Leda sisters' lives. Meanwhile, Cosima appears to be rebounding from her illness, while Alison and Donnie face newfound financial woes. But when the menace of Castor rears its head once more, Sarah and her entire family must come together to survive.", ep_time: "09:00" ,ep_date: "2015-04-19", ep_broadcast: "BBC America")
aS03E02_m7 = Episode.create(ep_number: "S03E02", ep_title: "Transitory Sacrifices of Crisis ", ep_plot: "Castor pursues the Leda clones for original tissue samples. Helena, who is pregnant and imprisoned, is examined by a mysterious new villain. The Castor boys are also out to play, toying with a frightened young woman, Patty, in a sexy switcheroo that ultimately sets Sarah - and Art - hot on the Castor trail. But it's not all fun and games for the Castor boys, as Sarah gleans they may have a mysterious defect that puts their lives in peril.", ep_time: "09:00" ,ep_date: "2015-04-26", ep_broadcast: "BBC America")
aS03E03_m7 = Episode.create(ep_number: "S03E03", ep_title: "Formalized, Complex, and Costly ", ep_plot: "Leda and Castor are both on the hunt for original clone DNA. On-the-lam, Mark and Gracie pursue new leads to find the samples that might set them free, while Art and Sarah reunite to track them down. Meanwhile, Cosima and Scott try to learn more about Castor's biology and Alison's new money-making venture is going gangbusters. A shocking revelation about the Castor-Leda connection leaves the sisters reeling, just before Sarah witnesses a deadly Prolethean-Castor face-off.", ep_time: "09:00" ,ep_date: "2015-05-03", ep_broadcast: "BBC America")
aS03E04_m7 = Episode.create(ep_number: "S03E04", ep_title: "Newer Elements of Our Defense ", ep_plot: "Sarah's fate hangs in the balance as she tries to save her sister.", ep_time: "09:00" ,ep_date: "2015-05-10", ep_broadcast: "BBC America")
aS03E05_m7 = Episode.create(ep_number: "S03E05", ep_title: "Scarred by Many Past Frustrations ", ep_plot: "Sarah and Helena suffer a strained reunion; the Leda family worries about Sarah's absence.", ep_time: "09:00" ,ep_date: "2015-05-17", ep_broadcast: "BBC America")
aS03E06_m7 = Episode.create(ep_number: "S03E06", ep_title: "Certain Agony of the Battlefield ", ep_plot: "Paul learns the truth about Coady's plans for Castor and has no choice but to make a dangerous play.", ep_time: "09:00" ,ep_date: "2015-05-24", ep_broadcast: "BBC America")
aS03E07_m7 = Episode.create(ep_number: "S03E07", ep_title: "Community of Dreadful Fear and Hate ", ep_plot: "Sarah and Helena have managed to escape from the Castor compound, and arranging with Mrs. S are awaiting Benjamin's arrival in the Mexican desert to retrieve them. However, they are surprised to see that their retriever is Mrs. S herself. This meeting allows for a showdown between Helena and Mrs. S, the former who wants to kill the latter for selling her out. With Cosima's new relationship with Shay being strong, Cosima is having problems dealing with Delphine, whether it be on a professional or personal level. Cosima feels like betraying a request by Delphine without...", ep_time: "09:00" ,ep_date: "2015-05-31", ep_broadcast: "BBC America")
aS03E08_m7 = Episode.create(ep_number: "S03E08", ep_title: "Ruthless in Purpose, and Insidious in Method ", ep_plot: "Ruthless in Purpose, and Insidious in Method Rachel bargains for her freedom with decoding Duncan's Moreau book.", ep_time: "09:00" ,ep_date: "2015-06-07", ep_broadcast: "BBC America")
aS03E09_m7 = Episode.create(ep_number: "S03E09", ep_title: "Insolvent Phantom of Tomorrow ", ep_plot: "Clone Club heads to London to track down the Castor Original, but their enemies follow closely.", ep_time: "09:00" ,ep_date: "2015-06-14", ep_broadcast: "BBC America")
aS03E10_m7 = Episode.create(ep_number: "S03E10", ep_title: "History Yet to Be Written ", ep_plot: "Kendall may be the key to stop Castor; the sisters appear to be thwarting their most dangerous foe.", ep_time: "09:00" ,ep_date: "2015-06-21", ep_broadcast: "BBC America")

aS04E01_m7 = Episode.create(ep_number: "S04E01", ep_title: "The Collapse of Nature ", ep_plot: "A flashback to Beth Childs' final investigation, days before her suicide.", ep_time: "09:00" ,ep_date: "2016-04-15", ep_broadcast: "BBC America")
aS04E02_m7 = Episode.create(ep_number: "S04E02", ep_title: "Transgressive Border Crossing ", ep_plot: "After fleeing Iceland, Sarah begins searching for M.K. and uncovers new clues to Beth's breakdown. Scott learns Kendall Malone is hiding something.", ep_time: "09:00" ,ep_date: "2016-04-22", ep_broadcast: "BBC America")
aS04E03_m7 = Episode.create(ep_number: "S04E03", ep_title: "The Stigmata of Progress ", ep_plot: "As Sarah scrambles to learn more about her implant, Alison and Donnie take a drastic step to help. Meanwhile, Kira has a disturbing vision.", ep_time: "09:00" ,ep_date: "2016-04-29", ep_broadcast: "BBC America")
aS04E04_m7 = Episode.create(ep_number: "S04E04", ep_title: "From Instinct to Rational Control ", ep_plot: "While Cosima examines Leekie's boy, Felix and Donnie pose as a couple to learn more about a fertility clinic. Sarah discovers M.K. has her own agenda.", ep_time: "09:00" ,ep_date: "2016-05-06", ep_broadcast: "BBC America")
aS04E05_m7 = Episode.create(ep_number: "S04E05", ep_title: "Human Raw Material ", ep_plot: "A risky cover mission at Brightborn yields several big surprises. The rift between Sarah and Felix grows as she checks up on Adele.", ep_time: "09:00" ,ep_date: "2016-05-13", ep_broadcast: "BBC America")
aS04E06_m7 = Episode.create(ep_number: "S04E06", ep_title: "The Scandal of Altruism ", ep_plot: "Seeing that it is the best overall solution yet not perfect by any means, Sarah and Cosima decide with Kendall's OK to set up an agreement with Susan Duncan, which they will not divulge to Mrs. S. until everything is arranged as they know she won't like what they've done. That agreement is an agent representing Susan will remove the bot from Sarah's cheek, with Cosima on site to ensure Sarah's safety. As Scott and Cosima have not yet come up with a \"cure\" for Cosima and the other affected Leda clones, they in turn will provide their research and Kendall to Susan, with...", ep_time: "09:00" ,ep_date: "2016-05-20", ep_broadcast: "BBC America")
aS04E07_m7 = Episode.create(ep_number: "S04E07", ep_title: "The Antisocialism of Sex ", ep_plot: "TBA", ep_time: "09:00" ,ep_date: "2016-05-27", ep_broadcast: "BBC America")
aS04E08_m7 = Episode.create(ep_number: "S04E08", ep_title: "The Redesign of Natural Objects ", ep_plot: "TBA", ep_time: "09:00" ,ep_date: "2016-06-03", ep_broadcast: "BBC America")
aS04E09_m7 = Episode.create(ep_number: "S04E09", ep_title: "The Mitigation of Competition ", ep_plot: "TBA", ep_time: "09:00" ,ep_date: "2016-06-10", ep_broadcast: "BBC America")
aS04E10_m7 = Episode.create(ep_number: "S04E10", ep_title: "From Dancing Mice to Psychopaths ", ep_plot: "TBA", ep_time: "09:00" ,ep_date: "2016-06-17", ep_broadcast: "BBC America")

m1.actors << [a1, a2, a3, a4, a5, a6]
m2.actors << [a7, a8, a9, a10]
m3.actors << [a11, a12, a13, a14]
m4.actors << [a15, a16, a17, a18, a19, a20]
m5.actors << [a21, a22, a23, a24, a25]
m6.actors << [a26, a27, a28, a29]
m7.actors << [a30, a31, a32, a33, a34, a35, a36]
m7.episodes << [aS01E01_m7, aS01E02_m7, aS01E03_m7, aS01E04_m7,  aS01E05_m7, aS01E06_m7, aS01E07_m7, aS01E08_m7, aS01E09_m7, aS01E10_m7, aS02E01_m7, aS02E02_m7, aS02E03_m7, aS02E04_m7, aS02E05_m7, aS02E06_m7, aS02E07_m7, aS02E08_m7, aS02E09_m7, aS02E10_m7, aS03E01_m7, aS03E02_m7, aS03E03_m7, aS03E04_m7, aS03E05_m7, aS03E06_m7, aS03E07_m7, aS03E08_m7, aS03E09_m7, aS03E10_m7, aS04E01_m7, aS04E02_m7, aS04E03_m7, aS04E04_m7, aS04E05_m7, aS04E06_m7, aS04E07_m7, aS04E08_m7, aS04E09_m7, aS04E10_m7]